### ISSUE TITLE
Autograder Consistency Error

### ISSUE THREAD

**Issue by clark-student-test** [LaunchCodeEducation/js-independent-track#43]
## Permalink

https://education.launchcode.org/js-independent-track/assignments/scrabble-scorer.html#b-add-and-organize-scoring-algorithms

## Issue

The Autograder for Assignment 2 expects to call scoringFunction not scorerFunction, which causes the autograder to fail incorrectly.

## (Optional) Screenshot

![image](https://user-images.githubusercontent.com/78670606/122477928-251e9900-cf8e-11eb-9726-e804c37ebce8.png)

**Comment by jimflores5** [comment]
Resolved, thanks!
